title: Our diversity
description: > # this means to ignore newlines until "baseurl:"
  This tool will help you visualise your progress on improving diversity in your company.
baseurl: "" # the subpath of your site, e.g. /blog
sass:
  sass_dir: _scss
  style: compressed
markdown: kramdown
